#server:
#  applicationConnectors:
#  - type: http
#    port: 80
#  adminConnectors:
#  - type: http
#    port: 81
server:
  type: simple
  applicationContextPath: /
  #adminContextPath: /admin # If you plan to use an admin path, you'll need to also use non-root app path
  connector:
    type: http
    port: 8080